


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_board
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

  thymeleaf3:
    decoupled-logic: true

logging:
  level:
    com.com.kh.board: debug

    org:
      springframework:
        web:
          servlet: debug
      apache:
        coyote:
          http11: debug
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
        SQL: debug

debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"